### ISSUE TITLE
Invalid length for SP and RE fields

### ISSUE THREAD

**Issue by princepaul** [zoranbosnjak/asterix-specs#19]
In the specs, SP and RE Fields are defined as explicit fields. 

Normally the first byte is the length of the field and that much bytes need to be skipped including the first byte to get the next field. Since the length of the field is not skipped, FSPEC for the next target is starting at the next byte which is creating problem in decoding.

**Comment by zoranbosnjak** [comment]
I am not sure I understand the issue. Where exactly is the length of the field not skipped? This operation (extracting data out of the explicit field) is performed on the decoder.  It looks like you are refering to some particular asterix decoder implementation. If so, which one?

**Comment by princepaul** [comment]
For eg, In CAT010 [https://github.com/zoranbosnjak/asterix-specs/blob/master/specs/cat010/cat-1.1.ast](url)

```
RE "Reserved Expansion Field"
        definition
            Expansion
        explicit

SP "Special Purpose Field"
        definition
            Special Purpose Field
        explicit 
```
SP and RE fields is defined as 1+ fields in the Release document which says 
`A stand-alone figure indicates the octet count of a fixed-length Data Item, 1+indicates a variable-length Data Item comprising a first part of one-octet followed by n-octets extents as necessary.`

So normally first byte is the length of the SP and RE fields.

If you want any sample pcap file, I can provide one with Special Purpose Field.

**Comment by zoranbosnjak** [comment]
The keyword "explicit" means exactly as you describe. That is: it specifies the field where the first byte is the length of the field (including the length byte itself) and the remaining bytes are actual data.  `RE` and `SP` fields from your example are OK in this respect. I am still not sure what seems to be the problem. Asterix-specs is not a parser. It just describes all items. The parser (some other project) must use the correct algorighm for parsing explicit or any other item type.

Please attach the pcap file, but please also explain how do you parse it? With wireshark or using some other tool?
Is there a problem with parsing or skipping the fields using your parsing tool?

**Comment by princepaul** [comment]
The problem is in wireshark. I thought the problem is in definition. Sorry about that.

After going through packet-asterix.c in wireshark, I found that the case EXP is commented out (line 47421). 

`                /*case EXP:
                    asterix_field_item = proto_tree_add_item (tree, *current_uap[i]->hf, tvb, offset + start, len, ENC_NA);
                    asterix_field_tree = proto_item_add_subtree (asterix_field_item, ett_asterix_subtree);
                    proto_tree_add_item (asterix_field_tree, hf_re_field_len, tvb, offset + start, 1, ENC_BIG_ENDIAN);
                    start++;
                    fspec_len = asterix_fspec_len (tvb, offset + start);
                    proto_tree_add_item (asterix_field_tree, hf_asterix_fspec, tvb, offset + start, fspec_len, ENC_NA);
                    dissect_asterix_fields (tvb, pinfo, offset + start, asterix_field_tree, category, (const AsterixField **)current_uap[i]->field);
                    break;*/`
                    
Will raise it as a bug there in wireshark.

**Comment by zoranbosnjak** [comment]
OK, thanks. Closing this issue.
Make sure to attach pcap file to the wireshark issue. It will be important there.
