### ISSUE TITLE
i062/510 Composed Track Number has nonstandard extents which is not represented in the spec files

### ISSUE THREAD

**Issue by victor-eh** [zoranbosnjak/asterix-specs#30]
In the Cat062 v1.17 spec i062/510 has a First Part which is the Master Track composed of three octets. The following extent describing Slave Tracks can actually repeat multiple times, while the AST file describes it as two extents. 

> Extendible data item, comprising a first part of three octets (Master
Track Number), followed by three-octet extents (Slave Tracks
Numbers).

> Structure of next Extents :

Note "extents" instead of the next extent as would be usual.

The AST file:
```
 510 "Composed Track Number"
        definition
            Identification of a system track.
        extended
            MIDENT "Master System Unit Identification"
                element 8
                    raw
            MTRACK "Master System Track Number"
                element 15
                    raw
            -
            SIDENT "Slave System Unit Identification"
                element 8
                    raw
            STRACK "Slave System Track Number"
                element 15
                    raw
            -
```

**Comment by zoranbosnjak** [comment]
@victor-eh 
Indeed, there is a problem. Do you have any sample data of category 062, containing item 510 with multiple extents? A single datagram would be sufficient, together with correct decoding of the same datagram.

**Comment by victor-eh** [comment]
Unfortunately I do not have a sample, this was just a discrepancy discovered while looking into using the specs.
