### ISSUE TITLE
Cat004 1.12 i004/170 Subfield #8 Mode-S Identifier Aircraft 1 should be StringICAO and not StringASCII

### ISSUE THREAD

**Issue by victor-eh** [zoranbosnjak/asterix-specs#32]
![image](https://github.com/user-attachments/assets/88729dd9-a6e2-41cd-a682-764926e42278)
Found while running tests.

The same is true for i004/171 Subfield #8 Mode-S Identifier Aircraft 2

**Comment by zoranbosnjak** [comment]
Thanks, fixed in 4a97e656105648f7e56f0256979d3c18a0795baf.
